# Generated by Django 5.2.4 on 2025-07-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's phone number - must be 11 digits, without the country code", max_length=11, null=True, unique=True),
        ),
    ]
