# Generated by Django 5.2.4 on 2025-07-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='flagged_for_fraud',
            field=models.BooleanField(default=False, help_text='Indicates if the customer has been flagged for suspicious activity.', verbose_name='Flagged for Fraud'),
        ),
    ]
