# Generated by Django 5.2.4 on 2025-07-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customer_phone_number_baseuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='The date of birth of the user. Required for customers.', null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='first_name',
            field=models.CharField(help_text='The first name of the user. Required for all users.', max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='last_name',
            field=models.CharField(help_text='The last name of the user. Required for all users.', max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's phone number - must be 11 digits, without the country code. Required for customers.", max_length=11, null=True, unique=True),
        ),
    ]
