# Generated by Django 5.2.4 on 2025-07-05 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0003_alter_loanapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for flagging the transaction as potential fraud.')),
                ('resolved', models.BooleanField(default=False, help_text='Indicates whether the fraud flag has been resolved.')),
                ('comments', models.TextField(blank=True, help_text='Additional comments or notes regarding the fraud flag.')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to='loans.loanapplication')),
            ],
        ),
    ]
