# Generated by Django 5.2.4 on 2025-07-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudflag',
            name='reason',
            field=models.CharField(choices=[('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('INCOMPLETE_KYC', 'Incomplete KYC'), ('INCONSISTENT_INFORMATION', 'Inconsistent Information'), ('HIGH_RISK_PROFILE', 'High Risk Profile'), ('UNUSUAL_TRANSACTION', 'Unusual Transaction'), ('INACTIVE_DEBIT_CARD', 'Inactive Debit Card'), ('DIRECT_DEBIT_FAILURE', 'Direct Debit Failure'), ('OTHER', 'Other')], help_text='Reason for flagging the transaction as potential fraud.', max_length=50),
        ),
    ]
