# Generated by Django 5.2.4 on 2025-07-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, help_text='Amount needed by the customer for the loan', max_digits=10)),
                ('purpose', models.CharField(choices=[('PERSONAL', 'Personal'), ('BUSINESS', 'Business'), ('EDUCATION', 'Education'), ('MEDICAL', 'Medical'), ('OTHER', 'Other')], help_text='Purpose of the loan application', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged for Fraud')], default='pending', help_text='Current status of the loan application', max_length=20)),
                ('date_applied', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the loan application was submitted')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the loan application was last updated')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-date_applied'],
            },
        ),
    ]
