# Generated by Django 5.2.4 on 2025-07-05 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='user',
            field=models.ForeignKey(help_text='Customer applying for the loan', on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', related_query_name='loan_application', to='users.customer'),
        ),
    ]
