# Generated by Django 5.2.4 on 2025-07-06 11:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loanapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='amount_requested',
            field=models.DecimalField(decimal_places=2, help_text='Amount needed by the customer for the loan', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1000.00')), django.core.validators.MaxValueValidator(Decimal('5000000.00'))]),
        ),
    ]
