name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: core.settings

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: install UV
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: install dependencies -- we don't care about the updating lock file here
        run: |
          uv venv --python=python3.13
          uv pip install --upgrade pip
          uv sync --no-install-project --frozen

      - name: apply migrations
        run: |
          uv run python manage.py migrate --noinput

      - name: tests + coverage
        run: |
          uv run pytest

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: push report  to codecov
        uses: codecov/codecov-action@v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: unittests
          name: codecov-coverage-report
