name: Run tests

on: [push, pull_request]
workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: core.settings

    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: install UV
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: install dependencies -- we don't care about the updating lock file here
        run: |
          uv venv --python=python3.13
          uv pip install --upgrade pip
          uv sync --locked --frozen

      - name: apply migrations
        run: |
          uv run python manage.py migrate --noinput

      - name: tests + coverage
        run: |
          uv run pytest --ds=your_project.settings \
            --cov=your_app \
            --cov-report=xml \
            --cov-report=html \
            --cov-fail-under=80

      - name: push report  to codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          fail_ci_if_error: true
          flags: unittests
          name: codecov-coverage-report
